### ISSUE TITLE
wrong main entry in package.json

### ISSUE THREAD

**Issue by mattecapu** [aickin/react-raw-html#1]
Try in an empty folder

``` bash
npm install react-raw-html
node -e "require('react-raw-html')"
```

You will get

```
Error: Cannot find module 'react-raw-html'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:262:27)
    at bound (domain.js:287:14)
    at REPLServer.runBound [as eval] (domain.js:300:12)
    at REPLServer.<anonymous> (repl.js:427:12)
    at emitOne (events.js:82:20)
```

Because `package.json` lists `build/RawHtml-server.js` as the main file, yet you didn't published the `build` folder (possibly because there is no `.npmignore` file, thus npm defaults to `.gitignore` where `build` is ignored).

**Comment by aickin** [comment]
Thanks for the PR, and sorry for not testing the uploaded code; should work now in v0.4.0.

**Comment by mattecapu** [comment]
You're welcome
